defaults:
  - _self_
  - paths: default.yaml
  - datamodule: shapenet.yaml
  - evaluator: default.yaml 
  - model: null
  - experiment: null

exp_name: null

test_batch_size: 4

world_size: 1
local_rank: -1
dist_url: 'env://'
dist_on_itp: False

ckpt_name: False
ckpt_resume: False